jwt:
  secret: blahblahblah
server:
  error:
    path: /user/error
    whitelabel:
      enabled: false
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/securecapita
    password: root
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  sql:
    init:
      mode: never
      continue-on-error: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: naveenjohn942@gmail.com
    password: yahz hzmb jhsw eiik

    properties:
      mail:
        smtp:
          writetimeout: 5000
          connectiontimeout: 5000
          timeout: 5000
          auth: true
          starttls:
            enable: true
            required: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
